version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=telegraphzs
      - DB_CONNECTION=mongodb://telegraphuser:telegraphpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:4.4
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=telegraphuser
      - MONGO_INITDB_DATABASE=telegraphzs
      - MONGO_INITDB_ROOT_PASSWORD=telegraphpass
volumes:
  dbdata:
